on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      salad: ${{ steps.step1.outputs.fruit }}
    steps:
      - id: step1
        uses: ./
        with:
          tool: "fork"
      - id: step2
        run: echo "::set-output name=output1::${{steps.step1.outputs.chain}}"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
